Repository mapbox/mapbox-java, pull requests merged in 2018-04, with the labels that each got.

#804 Add voiceLocale to DirectionsRoute and update test fixtures
  Makefile
  services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java
  services-directions/src/test/java/com/mapbox/api/directions/v5/models/DirectionsRouteTest.java
  services-directions/src/test/resources/directions_annotations_v5.json
  services-directions/src/test/resources/directions_v5.json
  services-directions/src/test/resources/directions_v5_banner_text.json
  services-directions/src/test/resources/directions_v5_banner_with_shield.json
  services-directions/src/test/resources/directions_v5_fixtures_rotary.json
  services-directions/src/test/resources/directions_v5_max_speed_annotation.json
  services-directions/src/test/resources/directions_v5_precision_6.json
  services-directions/src/test/resources/directions_v5_roundabout_exits.json
  services-directions/src/test/resources/directions_v5_traffic.json
  services-directions/src/test/resources/directions_v5_voice_banner.json
  services-directions/src/test/resources/directions_v5_voice_invalid.json
Labels: Directions

#805 replaced mapbox services README image with Mapbox Java
  .github/mbxservice-logo.png
Labels: Documentation

#806 README update/fixes
  README.md
Labels: Documentation, Ready For Review
