Repository mapbox/mapbox-java, pull requests merged in 2018-09, with the labels that each got.

#883 Additions/tweaks for missing javadocs
  services-directions/src/main/java/com/mapbox/api/directions/v5/models/MaxSpeed.java
  services-speech/src/main/java/com/mapbox/api/speech/v1/MapboxSpeech.java
Labels: Documentation, Ready For Review

#886 The first and last positions should be equivalent in polygon ring
  services-turf/src/main/java/com/mapbox/turf/TurfTransformation.java
  services-turf/src/test/resources/turf-transformation/circle_out.json
Labels: Bug, Ready For Review, refactor

#876 java 7 downgrade
  build.gradle
  services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteLegTest.java
  services-geojson/src/main/java/com/mapbox/geojson/Geometry.java
  services-geojson/src/main/java/com/mapbox/geojson/gson/GeometryGeoJson.java
  services-geojson/src/test/java/com/mapbox/geojson/GeometryTest.java
Labels: SEMVER-MAJOR
