Repository mapbox/mapbox-java, pull requests merged in 2018-08, with the labels that each got.

#862 Release v3.4.0
  CHANGELOG.md
  gradle.properties
  services-core/gradle.properties
  services-geojson/gradle.properties
  services-turf/gradle.properties
  services/gradle.properties
Labels: release

#870 Remove mention of repo test app from root README
  README.md
Labels: Bug, Documentation

#860 Support for Tilequery API
  Makefile
  samples/build.gradle
  samples/src/main/java/com/mapbox/samples/BasicTilequery.java
  services-tilequery/.gitignore
  services-tilequery/build.gradle
  services-tilequery/src/main/java/com/mapbox/api/tilequery/MapboxTilequery.java
  services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryCriteria.java
  services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryService.java
  services-tilequery/src/main/java/com/mapbox/api/tilequery/models/package-info.java
  services-tilequery/src/main/java/com/mapbox/api/tilequery/package-info.java
  services-tilequery/src/test/java/com/mapbox/api/tilequery/MapboxTilequeryTest.java
  services-tilequery/src/test/java/com/mapbox/api/tilequery/TilequeryTestUtils.java
  services-tilequery/src/test/resources/tilequery-all-params.json
  services-tilequery/src/test/resources/tilequery.json
  services/build.gradle
  settings.gradle
Labels: Ready For Review
