Repository mapbox/mapbox-java, pull requests merged in 2020-03, with the labels that each got.

#1123 RouteOptions parsing fixes
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/ParseUtils.java
  services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
Labels: Bug

#1126 Updated SNAPSHOT link in README
  README.md
Labels: Documentation, Ready For Review

#1132 Release 5.1.0-beta.2
  CHANGELOG.md
Labels: release

#1133 Adding flexibility to Matrix API builder to set custom max coordinate list size limit
  services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
  services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java
  services-matrix/src/test/java/com/mapbox/api/matrix/v1/MapboxMatrixTest.java
Labels: Matrix, Ready For Review

#1135 Release 5.1.0
  CHANGELOG.md
  README.md
Labels: Ready For Review, release
