Repository mapbox/mapbox-java, pull requests merged in 2020-01, with the labels that each got.

#1084 Remove references to enterprise requirement from geocoding docs
  services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingCriteria.java
  services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingService.java
  services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
Labels: Approved, Ready For Review

#1098 Add banner component type
  services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java
Labels: Directions, Ready For Review

#1097 Directions junction view api
  services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java
  services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerInstructions.java
  services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerView.java
  services-directions/src/test/java/com/mapbox/api/directions/v5/models/JunctionViewResponseTest.java
Labels: Ready For Review

#1099 Removing deprecated 4.x.x code before SEMVER major 5.0.0 release
  services-geojson/src/main/java/com/mapbox/geojson/gson/BoundingBoxDeserializer.java
  services-geojson/src/main/java/com/mapbox/geojson/gson/BoundingBoxSerializer.java
  services-geojson/src/main/java/com/mapbox/geojson/gson/CoordinateTypeAdapter.java
  services-geojson/src/main/java/com/mapbox/geojson/gson/GeometryDeserializer.java
  services-geojson/src/main/java/com/mapbox/geojson/gson/GeometryTypeAdapter.java
  services-geojson/src/main/java/com/mapbox/geojson/gson/PointDeserializer.java
  services-geojson/src/main/java/com/mapbox/geojson/gson/PointSerializer.java
  services-geojson/src/test/java/com/mapbox/geojson/gson/BoundingBoxDeserializerTest.java
  services-geojson/src/test/java/com/mapbox/geojson/gson/GeometryDeserializerTest.java
  services-geojson/src/test/java/com/mapbox/geojson/gson/PointDeserializerTest.java
  services-geojson/src/test/java/com/mapbox/geojson/gson/PointSerializerTest.java
  services-isochrone/src/main/java/com/mapbox/api/isochrone/IsochroneService.java
Labels: Ready For Review, SEMVER-MAJOR

#1047 Rename references of `mapIds` to `tileSetIds`
  samples/src/main/java/com/mapbox/samples/BasicTilequery.java
  services-tilequery/src/main/java/com/mapbox/api/tilequery/MapboxTilequery.java
  services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryService.java
  services-tilequery/src/test/java/com/mapbox/api/tilequery/MapboxTilequeryTest.java
Labels: SEMVER-MAJOR, Tilequery, refactor, ⚠️ DO NOT MERGE

#1101 Release 5.0.0
  CHANGELOG.md
  README.md
Labels: Ready For Review

#1110 Add toBuilder() method
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/WalkingOptions.java
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
  services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
  services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/WalkingOptionsTest.java
Labels: refactor

#1109 Bumped StaticMapCriteria constant style strings to new versions
  services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/StaticMapCriteria.java
  services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/MapboxStaticMapTest.java
Labels: Ready For Review, Static Image, Static map

#1111 Removed typo in BannerView class javadocs
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerView.java
Labels: Documentation, Ready For Review

#1114 Release 5.1.0-beta.1
  CHANGELOG.md
Labels: release

#1116 Bumped StaticMapCriteria guidance day and night versions to v4
  services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/StaticMapCriteria.java
Labels: Ready For Review, Static Image, Static map
