Repository mapbox/mapbox-java, pull requests merged in 2022-04, with the labels that each got.

#1390 Codecov is back
  .circleci/config.yml
  codecov.yml
  gradle/dependencies.gradle
  gradle/jacoco.gradle
  scripts/coverage.sh
Labels: Test

#1395 Revert `experimental EV routing request and response parameters`
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsWaypoint.java
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ExperimentalWaypointMetadata.java
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegAnnotation.java
  services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
  services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
  services-directions-models/src/test/resources/route_options_v5.json
  services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsService.java
  services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
  services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
  services-directions/src/test/resources/directions_v5_ev_experimental.json
  services-directions/src/test/resources/route_options_v5.json
Labels: release blocker

#1424 MapMatching: added ignore param
  services-matching/src/main/java/com/mapbox/api/matching/v5/MapMatchingService.java
  services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
  services-matching/src/main/java/com/mapbox/api/matching/v5/models/MapMatchingMatching.java
  services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
Labels: Map Matching

#1425 Add `v6.5.0-beta.3` `CHANGELOG` entry
  CHANGELOG.md
Labels: Ready For Review
